lang = {
    'en': {
        'status_base': "Important message from the Songmasters: {}",
        'status_none': "Have fun and love Treecko and Mudkip!",
        'must_set_host': "You must set DSC host!",
        'info_date_str': " until {}",
        'signup_phase_info': ":clipboard: Signing up open{}!",
        'desc_test': "Dies ist ein Test ob ich zwei Description-Sachen einbauen kann.",
        'current_host': "Current Host",
        'sign_up': "Sign up",
        'voting_phase_info': ":incoming_envelope: Voting is open{}",
        'votings_to': "Votings to",
        'all_songs': "All songs",
        'yt_playlist': "Youtube playlist",
        'config_error_reset': "Configuration error. Please reset dsc configuration.",
        'config_error': "DSC configuration error, config values:",
        'new_host_set': "New host set.",
        'phase_set': "{} state set.",
        'invalid_phase': "Invalid dsc state.",
        'yt_link_set': "New Youtube playlist link set.",
        'state_end_set': "New state end date set.",
        'status_set': "New status message set.",
        'archiv_info': "Die Gewinner*Innen des bisherigen DSC! Die vollständige Liste inklusive Hall of Fame: https://docs.google.com/spreadsheets/d/1HH42s5DX4FbuEeJPdm8l1TK70o2_EKADNOLkhu5qRa8/edit#gid=1757913329",
        'archiv_1': "DSC 1 (05/18), mit 130P",
        'sieger_1': "**Ozan** mit 'The Ballad of Mona Lisa' von 'Panic! At the Disco'",
        'archiv_2': "DSC 2 (08/18), mit 152P",
        'sieger_2': "**RBF** mit 'In My Mind' von 'Dynoro feat. Gigi D'Agostino",
        'archiv_3': "DSC 3 (11/18), mit 135P",
        'sieger_3': "**CFlyer95** mit 'In the Shadows' von 'The Rasmus'",
        'archiv_4': "DSC 4 (02/19), mit 120P",
        'sieger_4': "**Splitt13** mit 'Go To War' von 'Nothing More'",
        'archiv_5': "DSC 5 (05/19), mit 204P",
        'sieger_5': "**Lubadubs!** mit 'Gravity' von 'Against the Current'",
        'archiv_6': "DSC 6 (08/19), mit 179P",
        'sieger_6': "**Splitt13** mit 'Moskau' von 'Dschingis Khan'",
        'archiv_7': "DSC 7 (11/19), mit 182P",
        'sieger_7': "**Ikarus** mit 'Hate Conquers All' von 'Anti-Flag'",
        'archiv_8': "DSC 8 (03/20), mit 114P",
        'sieger_8': "**Janido** mit 'Make Me Wanna Cry' von 'The Pretty Reckless'", 
        'archiv_9': "DSC 9 (04/20), mit 203P",
        'sieger_9': "**Kristoph** mit 'Herz? Verloren!' von 'Farin Urlaub'",
        'archiv_10': "DSC 10 (08/20), mit 41P",
        'sieger_10': "**Danny** mit ALLEN LIEDERN DER WELT!"
        }
    }