name: Analysing missing lang strings

on:
  pull_request:
    branches:
      - development
      - release
      - hotfix
  push:
    branches:
      - development
      - release
      - hotfix

jobs:
  langdiff:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Analysing missing lang strings
      run: |
        python tools/langdiff.py
